my_string = input("Введите ваши (Фамилию, Имя ,Отчество) через пробел: ")
number_of_characters = len(my_string)
print("кол-во введенных символов:", number_of_characters)
print("Здравствуйте, ", my_string)
print(my_string.upper())
print(my_string.lower())
print(my_string. replace(" ",""))
print(my_string[0])
print(my_string[-1])